Roman trukhanovich cv
alexMbicycle/swapi-learn-java-react pull request #5
Opened 2023-02-10 12:10 UTC by TrukRoman

https://swapi-learn-java-react-sand.vercel.app/

2023-02-13 07:35 UTC, alexMbicycle requested changes

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/SimplePage.tsx
> +
There are shouldn't be empty spaces here.

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/SimplePage.tsx
> +
Here as well

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/bio/Bio.tsx
> +import styles from './styles.module.css';
please repalce css to styled.

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/body/education/Education.tsx
> +}));
Should be placed in additional file in the same directory as component. Also, if you are using 'styled' the name of it should have a prefix -Styled. For ex.: ItemStyled

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/body/education/Education.tsx
> +  }];
Objects like this should be placed in additional file (constants.ts)

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/body/education/Education.tsx
> +      {' '}
Can be removed

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/body/education/Education.tsx
> +                justifyContent: 'left',
Also to styled

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/experience/Experience.tsx
> +      <div className={styles.experience}>
No using div-s and p-s. Use MUI5 components

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/experience/styles.module.css
> +}
Please replace all to styled

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/footer/Footer.tsx
> +}));
Please replase to the additional file

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/footer/Footer.tsx
> +const githubIo = 'ivanov.github.io';
these variables as well

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/footer/Footer.tsx
> +              justifyContent: 'center',
To styled

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/footer/Footer.tsx
> +                    justifyContent: 'center',
To styled please

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/footer/Footer.tsx
> +                  marginRight: 0.5,
to styled please

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/footer/Footer.tsx
> +                    justifyContent: 'center',
as well as prev

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/footer/Footer.tsx
> +                    justifyContent: 'center',
All sx to styled please

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/header/Header.tsx
> +}));
to additional file

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/header/Header.tsx
> +Seeking to join BravDev to leverage experience with JavaScript.`;
also to additional file

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/header/Header.tsx
> +                height: 190,
Look at the picture. If I will resize the screen picture covers the right-side container with the text.
![image](https://user-images.githubusercontent.com/63092716/218397354-6a07cb52-782b-4247-ad9b-229a883e250a.png)

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/name-position/NamePosition.tsx
> +import styles from './styles.module.css';
Avoid using module.css

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/skills/Skills.tsx
> +          principles, user research, usability testing, and accessibility.
Please put raw text to the vdriable.

2023-02-13 07:35 UTC, alexMbicycle commented on src/components/styles.module.css
> +}
to styled

2023-02-13 13:07 UTC, TrukRoman commented
Applied all comments

2023-02-13 13:47 UTC, alexMbicycle requested changes

2023-02-13 13:47 UTC, alexMbicycle commented on src/components/body/experience/Experience.tsx
> +          justifyContent: 'left',
just ` textAlign='left' ` without sx

2023-02-13 13:47 UTC, alexMbicycle commented on src/components/body/experience/Experience.tsx
> +      {' '}
if you heed in spacing add `&nbsp;` instead of `{' '}`

2023-02-13 13:47 UTC, alexMbicycle commented on src/components/body/favorites/Favorites.tsx
> +                justifyContent: 'left',
textAlign='left'

2023-02-21 12:39 UTC, alexMbicycle requested changes

2023-02-21 12:39 UTC, alexMbicycle commented on src/components/body/education/ItemStyled.ts
> +  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
Are you using dark and light theme?

2023-02-21 12:39 UTC, alexMbicycle commented on src/components/body/experience/ItemStyled.ts
> +  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
As prev

2023-02-21 12:39 UTC, alexMbicycle commented on src/components/body/favorites/ItemStyled.ts
> +  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
As prev

2023-02-21 12:39 UTC, alexMbicycle commented on src/components/body/skills/ItemStyled.ts
> +  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
Also

2023-02-21 12:39 UTC, alexMbicycle commented on src/components/body/education/ItemStyled.ts
> +  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
I can't find swithch to dark theme.

2024-05-05 16:13 UTC, closed without merging